### ISSUE TITLE
What about "you serious about this?!"?

### ISSUE THREAD

**Issue by phmarek** [jnjcc/cl-qrencode#11]
Trying to encode some ASCII string I get the error `"you serious about this?!"` in `CL-QRENCODE::TERMINATOR`.

Why do I get that error?

**Comment by jnjcc** [comment]
Are you encoding some long string? Seems like it exceeds the data word capacity.

BTW, your last pull request #10 failed some test case, I haven't had time to figure out why, sorry.

**Comment by phmarek** [comment]
The code is

```lisp
(CL-QRENCODE:ENCODE-SYMBOL 
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxx?id=8C0F677B08DF2E6897015FF5&code=abcdefgh" 
  :VERSION 1 
  :LEVEL :LEVEL-L 
  :MODE NIL)
```

**Comment by jnjcc** [comment]
This is a bug. Fixed in 0de2d8a3877b499a9a0bbb0a9e1247056ae4311e.

Thanks!

**Comment by phmarek** [comment]
Thanks a lot!

I've pushed another fix - now the compile errors in `test/utils.lisp` are gone, only `VALIDATE-MASK0-7` has an unexpected result: `Expected (0 1 0) but saw (1 0 0)`.

**Comment by jnjcc** [comment]
TBH, I don't quite remember the meaning of this test case either, :-(

Might have to dig into it some later time when I'm free.

Thanks again.
