### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [jnjcc/cl-qrencode#3]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by jnjcc** [comment]
Fixed in 74c456d7dedfa733b0b89e9c5a33dbba4cdab99e. Thanks.
