### ISSUE TITLE
Wrong encoding for URL / bytes.

### ISSUE THREAD

**Issue by Ferada** [jnjcc/cl-qrencode#4]
(cl-qrencode:encode-png "herpderp")

results in a QR code that is being decoded to

    herpl�rp

(with `zbarimg`, an Android phone app and e.g. https://zxing.org/w/decode.jspx).

With the same settings, e.g. using `qrencode -8 -l M "herpderp" -o qrcode-correct.png` the data is decoded correctly, giving the resulting raw bytes

    40 86 86 57 27 06 46 57   27 00 ec 11 ec 11 ec 11

whereas the wrong sequence is

    40 86 86 57 27 06 c8 57   27 00 ec 11 ec 11 ec 11

With a bit of tracing I now think this is after the bit stream generation, so possibly in the EC coding functions.

(N.b. this is using an AFAIK fixed version of the padding, c.f. <https://github.com/jnjcc/cl-qrencode/pull/5>.)

**Comment by jnjcc** [comment]
Thanks for your feedback.

I've been busy at work lately, will take a look at it this weekend.

**Comment by jnjcc** [comment]
Fixed in b205f14a54047b842101d223eb2c20e1fa23845f.

Thanks again for your feedback.

**Comment by Ferada** [comment]
\o/ thanks so much!
