### ISSUE TITLE
Alnum mode is broken?

### ISSUE THREAD

**Issue by deadtrickster** [jnjcc/cl-qrencode#7]
Hello!
`(cl-qrencode-test::encode-alnum "qwe")` produces 

```
Argument X is not a NUMBER: NIL
[Condition of type SIMPLE-TYPE-ERROR]

Backtrace:
  0: (SB-KERNEL:TWO-ARG-* NIL 45)
  1: (CL-QRENCODE::PAIR->DECIMAL (NIL NIL NIL) 2)
      Locals:
        NUM = 2
        VALUES = (NIL NIL NIL)
  2: (CL-QRENCODE::ALNUM->BSTREAM (113 119 101))
  3: (CL-QRENCODE::SEGMENT->BSTREAM (:ALNUM 113 119 101) 1)
```

**Comment by jnjcc** [comment]
AFAIK, alphanumeric mode only works for uppercase characters.

So ```(cl-qrencode-test::encode-alnum "QWE")``` should work.

**Comment by deadtrickster** [comment]
yeah you are right, however maybe more user-friendly message is a good idea?

**Comment by jnjcc** [comment]
I think it might not matter that much.

After all, this function was meant for internal usage only, :-)
