### ISSUE TITLE
Non-scannable codes

### ISSUE THREAD

**Issue by deadtrickster** [jnjcc/cl-qrencode#8]
I'm encoding the following string "ca85ce19c091fdcffae37b9c9cb0207b2b2c82df867e8a489a3dbe43796aa7896130de17ec68af131d8a6ebfb7324f8e904fe9598614a1772be418e1d5660c0dqwevfd" with defaults.

![QR](http://i.imgur.com/I8PPu8g.png)

Neither my phone nor this service: https://zxing.org/w/decode.jspx can recognize/detect this generated qr code.

I tested this string using an online service:
![QR](https://api.qrserver.com/v1/create-qr-code/?data=ca85ce19c091fdcffae37b9c9cb0207b2b2c82df867e8a489a3dbe43796aa7896130de17ec68af131d8a6ebfb7324f8e904fe9598614a1772be418e1d5660c0dqwevfd)
 This code perfectly scans

I understand setting can differ but anyway.

**Comment by jnjcc** [comment]
This was introduced by the latest commit b205f14a54047b842101d223eb2c20e1fa23845f.
I didn't do regression test after that. My fault.

Fixed in d14c9854a49715ad6f0d685c36733b7bb99e6f0d.

Thanks.

**Comment by deadtrickster** [comment]
Maybe it's time to integrate with TravisCI for example? Let me know if you need help.

**Comment by jnjcc** [comment]
This project had not been under active development for quite some time, so...

Anyway, I will take a look at TravisCI some later time, :-)
